# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(height_field='image_height', upload_to='profile_pictures/', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.ForeignKey(blank=True, default='None', on_delete=django.db.models.deletion.CASCADE, to='Dictionary.Category'),
        ),
    ]
