# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dictionary', '0002_auto_20170515_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(blank=True, default='None', max_length=40),
        ),
    ]
