# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dictionary', '0010_auto_20170530_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Dictionary.Category'),
            preserve_default=False,
        ),
    ]
